project_name: "LoopSplat_SLAM_scannet"
dataset_name: "scan_net"
checkpoint_path: null
use_wandb: True
frame_limit: -1 # for debugging, set to -1 to disable
seed: 0
mapping:
  new_submap_every: 50
  map_every: 1
  iterations: 100
  new_submap_iterations: 100
  new_submap_points_num: 100000 
  new_submap_gradient_points_num: 50000 
  new_frame_sample_size: 30000 
  new_points_radius: 0.0001
  current_view_opt_iterations: 0.4 # What portion of iterations to spend on the current view
  alpha_thre: 0.6
  pruning_thre: 0.5
  submap_using_motion_heuristic: False
tracking:
  gt_camera: False
  w_color_loss: 0.6
  iterations: 200
  cam_rot_lr: 0.002
  cam_trans_lr: 0.01
  odometry_type: "const_speed"  # gt, const_speed, odometer
  help_camera_initialization: False # temp option to help const_init
  init_err_ratio: 5
  odometer_method: "hybrid" # hybrid or point_to_plane
  filter_alpha: True
  filter_outlier_depth: True
  alpha_thre: 0.98
  soft_alpha: True
  mask_invalid_depth: True
  enable_exposure: True
cam: 
  H: 480 
  W: 640
  fx: 577.590698
  fy: 578.729797
  cx: 318.905426
  cy: 242.683609
  depth_scale: 1.
  crop_edge: 12
lc: 
  min_similarity: 0.5
  pgo_edge_prune_thres: 0.25
  voxel_size: 0.02
  pgo_max_iterations: 500
  registration:
    method: "gs_reg"
    base_lr: 5.e-3
    min_overlap_ratio: 0.2
    use_render: True # use rendered image as target for registration 
  min_interval: 4
  final: False
  